export const COLORS = {
    red:"red",
    vanillaCream:"#fdf5e6",
    lime:"lime",
    green:"green",
    white:"white",
    pinkPearl:"#FFF2D7",
    blue:"blue",
    greyPearl:"#F6F5F2",
    tomato:"tomato",
    transparent:"transparent",
    yellow:"yellow",
    lightYellow: "#FFFFE0",
    black:"black",
    pureWhite:"#fff",
    orange:"orange",
    turquoise:"#00DFA2",
    gray:"gray",
    gunMetal: "#222831",
    DeepSkyBlue: "#00BFFF",
    darkTomato: "#FF6347",
    vividRed: "#FF204E",
    deepPink: "#ff1493",
    lightBlack: "#222831",
    lightGray: "#D3D3D3",
};